### ISSUE TITLE
服务器在国外使用报504

### ISSUE THREAD

**Issue by DavidZha1994** [Ysnsn/mimotion#13]
我在国外无法使用服务器，一直报504，兴许ip被ban掉了？

**Comment by Ysnsn** [comment]
@DavidZha1994 可能吧，我用的国内的

**Comment by DavidZha1994** [comment]
MBP-von-Yu (192.168.0.153) -> 49.233.94.119            2021-09-07T18:42:03+0200
Keys:  Help   Display mode   Restart statistics   Order of fields   quit
                                       Packets               Pings
 Host                                Loss%   Snt   Last   Avg  Best  Wrst StDev
 1. kabelbox.local                   95.0%    21    5.3   5.3   5.3   5.3   0.0
 2. 84.116.198.84                     0.0%    21   12.9  12.2  10.7  15.6   1.1
 3. 84.116.191.73                     0.0%    21   19.9  20.8  15.6  45.0   7.1
 4. de-dtm01a-rd04-ae-0-0.aorta.net   0.0%    21   19.8  17.7  15.4  23.5   2.2
 5. de-fra01b-rc1-ae-44-0.aorta.net   0.0%    20   18.5  19.0  16.0  25.3   2.5
 6. de-bfe18a-rt01-lag-1.aorta.net    0.0%    20   62.9  23.5  15.0  62.9  13.2
 7. ae32-100-pcr1.fnt.cw.net          0.0%    20   15.7  18.8  15.7  31.0   3.4
 8. ae36-xcr1.ltw.cw.net              0.0%    20   24.6  27.3  24.4  41.8   4.6
 9. ae29-xcr2.ash.cw.net              0.0%    20  101.0  98.0  94.8 103.8   2.3
10. 195.2.14.70                       0.0%    20   96.1 101.6  96.1 106.6   3.0
11. 202.97.92.173                     0.0%    20  177.0 179.5 172.3 185.3   3.6
12. 202.97.89.145                     0.0%    20  320.8 321.7 318.9 327.1   1.9
13. 202.97.81.169                     0.0%    20  322.6 320.8 316.4 329.2   3.1
14. 202.97.94.189                     0.0%    20  335.3 337.2 333.8 346.7   3.2
15. 218.30.28.50                     20.0%    20  334.5 335.0 331.9 338.5   1.9
16. 218.30.104.246                   80.0%    20  333.2 334.9 333.2 336.3   1.5
17. 36.110.203.230                   35.0%    20  334.2 342.9 333.8 370.6  13.3
18. (waiting for reply)
19. 49.233.94.119                    15.8%    20  339.9 335.2 332.3 342.0   2.7

**Comment by DavidZha1994** [comment]
但是能ping 通

**Comment by Ysnsn** [comment]
本地可以？

**Comment by DavidZha1994** [comment]
理论上应该可以，我之后试一下，主要是我用你的服务器写了一个ios捷径可以每天定时随机刷步数方便一点，要不然也还是得租个服务器或者电脑一直开着 感觉没有直接用你现成的方便 XD

**Comment by DavidZha1994** [comment]
而且你之前的服务器一直是可以用的，就是前段时间貌似改了地址 然后就不能用了
