### ISSUE TITLE
为什么无法同步微信步数？

### ISSUE THREAD

**Issue by yuwangi** [Ysnsn/mimotion#7]

**Comment by Ysnsn** [comment]
@yuwangi 等一会就会同步

**Comment by yuwangi** [comment]
这么强吗 老铁



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 阳光小饺子 ***@***.***&gt;
发送时间: 2021年6月14日 20:56
收件人: Ysnsn/mimotion ***@***.***&gt;
抄送: yuwangi ***@***.***&gt;, Mention ***@***.***&gt;
主题: 回复：[Ysnsn/mimotion] 为什么无法同步微信步数？ (#7)





 
@yuwangi 等一会就会同步

**Comment by yuwangi** [comment]
大佬，还是没有办法同步微信的步数  我看支付宝的已经生效了，  还需要配置什么吗？



***@***.***
 
发件人： 阳光小饺子
发送时间： 2021-06-15 11:16
收件人： Ysnsn/mimotion
抄送： yuwangi; Mention
主题： Re: [Ysnsn/mimotion] 为什么无法同步微信步数？ (#7)
Closed #7.
