### ISSUE TITLE
微信同步问题

### ISSUE THREAD

**Issue by yuwangi** [Ysnsn/mimotion#8]
微信同步 还是不行 ，  支付宝是可以的  而且小米运动无法同步到微信

**Comment by yuwangi** [comment]
github  action  QQ酷推 key 从哪里获取？

**Comment by yuwangi** [comment]
github action  只是消息推送是吗？   没有其他功能？

**Comment by Ysnsn** [comment]
@yuwangi 重新绑定微信试试

**Comment by Ysnsn** [comment]
@yuwangi 能定时

**Comment by yuwangi** [comment]
![image](https://user-images.githubusercontent.com/13346477/122036703-6f750e00-ce06-11eb-91f6-b7eb3d196fae.png)  小米同步微信 失败

**Comment by Ysnsn** [comment]
@yuwangi 不知道，没见过

**Comment by yuwangi** [comment]
ios 健康数据  也没有改动 ？  正常情况  健康数据 也会修改吗？

**Comment by Ysnsn** [comment]
@yuwangi 没用过，不知道啊

**Comment by yuwangi** [comment]
嗯嗯 好嘞    ~~~  辛苦啦  已经很好用了   我再研究研究
